<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-05-16T21:59:31Z" name="Default Suite" finished-at="2021-05-16T21:59:40Z" duration-ms="9235">
    <groups>
    </groups>
    <test started-at="2021-05-16T21:59:31Z" name="users-suite" finished-at="2021-05-16T21:59:40Z" duration-ms="9235">
      <class name="MockedTests">
        <test-method is-config="true" signature="setup()[pri:0, instance:MockedTests@4d1b0d2a]" started-at="2021-05-16T18:59:31Z" name="setup" finished-at="2021-05-16T18:59:31Z" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="instantiateDriver()[pri:0, instance:MockedTests@4d1b0d2a]" started-at="2021-05-16T18:59:31Z" name="instantiateDriver" finished-at="2021-05-16T18:59:36Z" duration-ms="4865" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- instantiateDriver -->
        <test-method signature="someTest()[pri:5, instance:MockedTests@4d1b0d2a]" started-at="2021-05-16T18:59:36Z" name="someTest" finished-at="2021-05-16T18:59:39Z" duration-ms="3293" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at MockedTests.someTest(MockedTests.java:68)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- someTest -->
        <test-method signature="someOtherTest()[pri:10, instance:MockedTests@4d1b0d2a]" started-at="2021-05-16T18:59:39Z" name="someOtherTest" finished-at="2021-05-16T18:59:40Z" duration-ms="515" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- someOtherTest -->
        <test-method signature="yetSomeOtherTest()[pri:15, instance:MockedTests@4d1b0d2a]" started-at="2021-05-16T18:59:40Z" name="yetSomeOtherTest" finished-at="2021-05-16T18:59:40Z" duration-ms="178" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- yetSomeOtherTest -->
        <test-method signature="almostTheLastTest()[pri:20, instance:MockedTests@4d1b0d2a]" started-at="2021-05-16T18:59:40Z" name="almostTheLastTest" finished-at="2021-05-16T18:59:40Z" duration-ms="178" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- almostTheLastTest -->
        <test-method signature="theLastTest()[pri:25, instance:MockedTests@4d1b0d2a]" started-at="2021-05-16T18:59:40Z" name="theLastTest" finished-at="2021-05-16T18:59:40Z" duration-ms="181" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- theLastTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:MockedTests@4d1b0d2a]" started-at="2021-05-16T18:59:40Z" name="tearDown" finished-at="2021-05-16T18:59:40Z" duration-ms="84" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- MockedTests -->
    </test> <!-- users-suite -->
  </suite> <!-- Default Suite -->
</testng-results>
